version:  '3.1'

services:
  core:
    container_name: pe-db_core
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "3000:3000"
  db:
    image: postgres
    container_name: pe-bot_pg
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    container_name: pe-bot_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "4000:8080"

